Neos:
  Fusion:
    defaultContext:
      NotFound.Context: MOC\NotFound\Fusion\Eel\Helper\ContextHelper
  Neos:
    fusion:
      autoInclude:
        MOC.NotFound: true
MOC:
  NotFound:
    uriPathSegment: 404
